config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :fotitos

  resources :posts

  get 'welcome/index'

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/fotito.rb
class Fotito < ActiveRecord::Base
	has_many :posts

	mount_uploader :imagen, FotoUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :fotito
	mount_uploader :foto, FotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fotitos_controller.rb
class FotitosController < ApplicationController
  before_action :set_fotito, only: [:show, :edit, :update, :destroy]

  # GET /fotitos
  # GET /fotitos.json
  def index
    @fotitos = Fotito.all
  end

  # GET /fotitos/1
  # GET /fotitos/1.json
  def show
  end

  # GET /fotitos/new
  def new
    @fotito = Fotito.new
  end

  # GET /fotitos/1/edit
  def edit
  end

  # POST /fotitos
  # POST /fotitos.json
  def create
    @fotito = Fotito.new(fotito_params)

    respond_to do |format|
      if @fotito.save
        format.html { redirect_to @fotito, notice: 'Fotito was successfully created.' }
        format.json { render :show, status: :created, location: @fotito }
      else
        format.html { render :new }
        format.json { render json: @fotito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotitos/1
  # PATCH/PUT /fotitos/1.json
  def update
    respond_to do |format|
      if @fotito.update(fotito_params)
        format.html { redirect_to @fotito, notice: 'Fotito was successfully updated.' }
        format.json { render :show, status: :ok, location: @fotito }
      else
        format.html { render :edit }
        format.json { render json: @fotito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotitos/1
  # DELETE /fotitos/1.json
  def destroy
    @fotito.destroy
    respond_to do |format|
      format.html { redirect_to fotitos_url, notice: 'Fotito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fotito
      @fotito = Fotito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fotito_params
      params.require(:fotito).permit(:nombre, :imagen)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :descripcion, :foto, :fotito_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	#before_action :authenticate_user!, except: [:show, :index]

	def index
		@posts = Post.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotitos_helper.rb
module FotitosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fotitos/_form.html.erb
<%= form_for(@fotito, :multipart => true) do |f| %>
  <% if @fotito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fotito.errors.count, "error") %> prohibited this fotito from being saved:</h2>

      <ul>
      <% @fotito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.file_field :imagen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotitos/edit.html.erb
<main>
	<section class="internoPost">
		<h1>Editing fotito</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @fotito %> |
		<%= link_to 'Back', fotitos_path %>


	</section>
</main>

app/views/fotitos/index.html.erb
<main>
  <section class="internoPost">
    <div class="contPost">
      <h1>Listing fotitos</h1>

      <table>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Imagen</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @fotitos.each do |fotito| %>
            <tr>
              <td><%= fotito.nombre %></td>
              <td><%= fotito.imagen %></td>
              <td><%= link_to 'Show', fotito %></td>
              <td><%= link_to 'Edit', edit_fotito_path(fotito) %></td>
              <td><%= link_to 'Destroy', fotito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <%= link_to 'Agregar mas fotos', new_fotito_path, :class=>"botonsillo" %>
    </div>
  </section>
</main>

app/views/fotitos/new.html.erb
<main>
	<section class="internoPost">
		<h1>New fotito</h1>

		<%= render 'form' %>

		<%= link_to 'Back', fotitos_path %>
	</section>
</main>

app/views/fotitos/show.html.erb
<main>
	<section class="internoPost">
		<p id="notice"><%= notice %></p>

		<p>
		  <strong>Nombre:</strong>
		  <%= @fotito.nombre %>
		</p>

		<p>
		  <img src="<%= @fotito.imagen %>">
		</p>

		<%= link_to 'Edit', edit_fotito_path(@fotito) %> |
		<%= link_to 'Back', fotitos_path %>
	</section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8" />
  <title>Panopticon</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'normalize', 'estilo', media: 'all', 'data-turbolinks-track' => true %>


  
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
      <div class="contenedor">
        <div class="logo">
          <figure>
            <a class="blog-logo" href="/">
                <img class="wenalogo" src="/assets/logo1.png" alt="">
            </a>
          </figure>
          <h2>Juan Bustamante</h2>
        </div>
        
        

        <nav>
            <ul>
                <li><a class="ancla" href=".galeria">Trabajos</a></li>
                <li><a class="ancla" href=".aboutMe">Sobre mi</a></li>
                
                <% if current_admin %>
                  <li>
                    <%= link_to 'Salir', destroy_admin_session_path, method: :delete %>
                  </li>
                  <li>
                    <%= link_to 'Nuevo', new_post_path %>
                  </li>
                <%else%>
                  <li>
                    <%= link_to 'Ingresa', new_admin_session_path %>
                  </li>
                <%end%>
            </ul>
        </nav>
      </div>
    </header>

  <%= yield %>


  <%= javascript_include_tag 'application','carrusel', 'script', 'data-turbolinks-track' => true %>

  <footer>
    <div class="imagBackground">
      <div class="imag"></div>
      <h2>Contacto</h2>
    </div>
  	<a class="mail" href="mailto:someone@example.com"><p>Por correo</p></a>
    <a class="git"href="https://github.com/oroborusm"><p>Mi cuenta de git</p></a>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </footer>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :multipart => true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.file_field :foto %>
  </div>
  <div class="field">
    <%= f.label :fotito_id %><br>
    <%= collection_select( :post, :fotito_id, Fotito.all, :id, :nombre, {}, { :multiple => false } ) %>
  </div>
  


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<main>
	<section class="internoPost">

		<h1>Editing post</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @post %> |
		<%= link_to 'Back', posts_path %>


	</section>
</main>

app/views/posts/index.html.erb
<main>
  <section class="internoPost">
    <div class="contPost">
      <h1>Mis trabajos</h1>
      <ul class="post-iterado">
        <% @posts.each do |post| %>
          <li data-id="<%= post.id %>">
            <figure style="background-image:url('<%= post.foto %>');">
            </figure>
            <div class="links">
              <%= link_to "#{post.titulo}", post, :class=>"titulo" %>

              <%= link_to '', post, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"cerrar" %>
            </div>
            
          </li>
        <% end %>
      </ul>

      <% if current_admin %>
        <%= link_to 'Crear nueva entrada', new_post_path, :class=>"botonsillo" %>
        <%= link_to 'Agregar mas fotos', fotitos_path, :class=>"botonsillo" %>
      <% end %>
    </div>

    
  </section>
</main>

app/views/posts/new.html.erb
<main>
	<section class="internoPost">
		<h1>New post</h1>

		<%= render 'form' %>

		<%= link_to 'Back', posts_path %>

	</section>
</main>

app/views/posts/show.html.erb
<main>
	<section class="internoPost">
		<p id="notice"><%= notice %></p>
		<h2><%= @post.titulo %></h2>
		<article class="post">
			<figure>
				<img src="<%= @post.foto %>" alt="">
			</figure>
			
			<p>
				<%= @post.descripcion %>
			</p>
		</article>

		<article class="detalle">
			<figure>
				<img src="<%= @post.fotito.imagen %>" alt="">
			</figure>
		</article>

		<div class="contPost">
			<ul>
				<% if current_admin %>
					<li>
						<%= link_to 'Back', posts_path , :class=>"botonsillo" %>	
					</li>
					<li>
						<%= link_to 'Edit', edit_post_path(@post) , :class=>"botonsillo" %>
					</li>
				<%else%>
					<li>
						<a href="/" class="botonsillo">Volver</a>
					</li>
				<%end%>
			</ul>
			
					
		</div>



	</section>
</main>

app/views/welcome/index.html.erb
   <div class="fijo">
	    <div class="bio">
	      <ul class="slide">
	        <li>
	          <figure>
	            <img src="/assets/diseno.png" alt="">
	            <figcaption>
	              <p>Diseñador Gráfico de pasión y profesión de día…</p>
	            </figcaption>
	          </figure>
	          
	        </li>

	        <li>
	          <figure>
	            <img src="/assets/codigo.png" alt="">
	            <figcaption>
	              <p>Front-end developer, por las noches …</p>
	            </figcaption>
	          </figure>
	        </li>
	      </ul>
	    </div>

	    <div class="fijoImg"></div>
	</div>
	
	<main>
		
		<section>
	        <article class="tools">
	          <ul class="dis">
	              <li >
	                  <figure>
	                      <img src="assets/ai.png" alt="">
	                      <figcaption></figcaption>
	                  </figure>
	              </li>
	              <li >
	                  <figure>
	                      <img src="assets/ps.png" alt="">
	                      <figcaption></figcaption>
	                  </figure>
	              </li>
	              <li >
	                  <figure>
	                      <img src="assets/id.png" alt="">
	                      <figcaption></figcaption>
	                  </figure>
	              </li>
	          </ul>

	          <ul>
	            <li>
	                <figure>
	                    <img src="assets/html.png" alt="">
	                    <figcaption></figcaption>
	                </figure>
	            </li>
	            <li>
	                <figure>
	                    <img src="assets/rails.png" alt="">
	                    <figcaption></figcaption>
	                </figure>
	            </li>
	            <li>
	                <figure>
	                    <img src="assets/css.png" alt="">
	                    <figcaption></figcaption>
	                </figure>
	            </li>
	            <li>
	                <figure>
	                    <img src="assets/js.png" alt="">
	                    <figcaption></figcaption>
	                </figure>
	            </li>
	            <li>
	                <figure>
	                    <img src="assets/sublime.png" alt="">
	                    <figcaption></figcaption>
	                </figure>
	            </li>
	            <li>
	                <figure>
	                    <img src="assets/styl.png" alt="">
	                    <figcaption></figcaption>
	                </figure>
	            </li>
	          </ul>
	        </article>
	        
	    </section>



		<section class="galeria">
			<div class="imagBackground">
				<div class="imag"></div>
				<h2>Trabajos</h2>
			</div>
			
			<div class="contPost">
				<ul class="post-iterado">
					<% @posts.each do |post| %>
						<li data-id="<%= post.id %>">
							<figure style="background-image:url('<%= post.foto %>');">
							</figure>
							
							<%= link_to "#{post.titulo}", post %>
							
						</li>
					<% end %>
				</ul>
			</div>
		</section>
		
		<section class="aboutMe">
			<div class="imagBackground">
				<div class="imag"></div>
				<h2>Sobre mí</h2>
			</div>
			<div class="about">
				<article class="inacap">
					<div class="cont">
						<h3>Inacap Valparaíso, Diseño Gráfico.</h3>
						<ul>
							<li>Ganador competencia Profusión.</li>
							<li>Finalista concurso de etiquetas cerveza artesanal Cranbell (ahora llamada BAC).</li>
							<li>Seminario de tecnologías para el diseño gráfico organizado por Inacap Valpo y Global Mac. </li>
						</ul>
						<p>Entre 2008 y 2010 alumno talleres de jornadas internacionales, Profesores: Santiago Pujol (Cuba), Julián Naranjo (Chile), Germán Montalvo (México).</p>
					</div>
				</article>

				<article class="laboral">
					<div class="cont">
						<h3>Laboral / Diseño web.</h3>
						<ul>
							<li>Diseñador gráfico en Officenter Viña del Mar (2011-2012).</li>
							<li>Diseñador gráfico en Partner Chile (2012-2013).</li>
							<li>Diseñador gráfico en Worket (start-up 2013). </li>
							<li>Capacitaciones varias en cursos online y presenciales. (Diseño y programación multimedia).</li>
						</ul>
						<p>"En este minuto me encuentro trabajando de forma freelance, en algunos proyectos de desarrollo web, desde el diseño de interfaces, hasta maquetación."</p>
					</div>
				</article>
			</div>
			

		</section>
	</main>